{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "user-service.fullname" . }}-allow-internal
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  # Allow internal service-to-service calls
  - from:
    - source:
        {{- if .Values.istio.authorization }}
        {{- if .Values.istio.authorization.internalCallers }}
        principals: {{ .Values.istio.authorization.internalCallers | toJson }}
        {{- end }}
        {{- end }}
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths: ["/api/v1/internal/*", "/api/v1/internal/**"]

  # Allow user endpoints (me, users) and public endpoints (health, docs)
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths:
          - "/api/v1/me"
          - "/api/v1/me/*"
          - "/api/v1/me/**"
          - "/api/v1/users/*"
          - "/api/v1/users/**"
          - "/api/v1/files"
          - "/api/v1/files/**"
          - "/api/v1/languages"
          - "/api/v1/languages/*"
          - "/api/v1/languages/**"
          - "/api/v1/favorites"
          - "/api/v1/favorites/**"
          - "/api/v1/translations"
          - "/api/v1/translations/**"
          - "/v3/api-docs/*"
          - "/v3/api-docs"
          - "/swagger-ui/*"
          - "/swagger-ui.html"
          - "/actuator/health"
          - "/actuator/health/*"
          - "/health"

  # Allow goal endpoints (RBAC enforced by application via @PreAuthorize)
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths:
          - "/api/v1/goals"
          - "/api/v1/goals/**"
{{- end }}
