{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "user-service.fullname" . }}-mtls
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.istio.mtls.mode | default "STRICT" }}
{{- end }}
